## Практическое задание. Часть 1.

In [1]:
import numpy as np

### Задание 1.
Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Решение:
- а) $AB$ и $BA$ не определены, так как в обоих случаях размерность столбцов у первой матрицы и размерность строк у второй не совпадают.
- б) только $AB$ определено (полученная размерность 2x3), так как размерность столбцов у первой матрицы и размерность строк у второй совпадают. В случае $BA$ - не определено (3 != 2). 
- в) $AB$ и $BA$ определены, в обоих случаях размерность столбцов у первой матрицы и размерность строк у второй совпадают. Размерность $AB$ = 8x8, $BA$ = 3x3.
- г) $AB$ и $BA$ определены, в обоих случаях размерность столбцов у первой матрицы и размерность строк у второй совпадают. Размерность $AB$ = 4x4, $BA$ = 4x4.

### Задание 2.
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Сначала займемся суммой:

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

Создадим функцию для подсчета суммы матриц:

In [3]:
def summa(A, B):
    summa = [[None for i in range(len(A))] for el in range(len(B[0]))]
    for i in range(len(A)):
        for j in range(len(A[0])):
            summa[i][j] = A[i][j] + B[i][j]
    return(summa)

summa(A,B)

[[5, -3], [3, 5]]

Проверим с помощью numpy:

In [4]:
A+B == summa(A,B)

array([[ True,  True],
       [ True,  True]])

"Произведение" матриц (Заодно здесь реализована функция для подсчета произведения матриц для задания N5):

In [5]:
def matrix_multiply(A, B):
    C = [[None for i in range(len(A))] for el in range(len(B[0]))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            sum = 0
            for k in range(len(A[0])):
                sum += A[i,k] * B[k,j]
            C[i][j] = sum
    return C

In [6]:
print('Произведение A*B = ',matrix_multiply(A, B))
print('Произведение B*A = ',matrix_multiply(B, A))

Произведение A*B =  [[4, -11], [12, -3]]
Произведение B*A =  [[1, -8], [15, 0]]


Проверим с использованием numpy:

In [7]:
print('Совпадает ли A*B в numpy и самостоятельно созданной функции? -', (matrix_multiply(A, B) == A.dot(B)).all())
print('Совпадает ли B*A в numpy и самостоятельно созданной функции? -', (matrix_multiply(B, A) == B.dot(A)).all())

Совпадает ли A*B в numpy и самостоятельно созданной функции? - True
Совпадает ли B*A в numpy и самостоятельно созданной функции? - True


### Задание 3.
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [8]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

Воспользуюсь самостоятельно созданной функцией summa() из прошлого задания.

In [9]:
summa(summa(3*A,-2*B),4*C)

[[11, -5], [9, -12]]

### Задание 4.
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [10]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [11]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

Воспользуюсь собственной функцией, созданной в Задании 2, а затем сверим полученные матрицы со значениями из numpy.dot()

In [12]:
print('Матрица корреляций:',matrix_multiply(A, A.T))

Матрица корреляций: [[17, 18, 11], [18, 29, 4], [11, 4, 13]]


In [13]:
print('Матрица ковариаций:',matrix_multiply(A.T, A))

Матрица ковариаций: [[45, 0], [0, 14]]


Сверяем с numpy.dot(), матрицы корреляций и ковариаций совпали.

In [14]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [15]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

## Задание 5.
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

Сделано в Задании 2 - функция matrix_multiply()

## Практическое задание. Часть 2.

### Задание 1.
Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Решение:

а) Вооружившись знанием, что для того, чтобы найти определитель в матрице размерности 2х2, нам необходимо умножить элементы главной диагонали и вычесть из этого произведение элементом другой диагонали, получаем, что определитель равен единицие, так как $sin^2x + cos^2x = 1$

In [16]:
from numpy.linalg import det

б) В треугольной матрице, нам достаточно перемножить элементы главной диагонали, для того, чтобы найти определитель матрицы. Определитель = 4 * 5 * 9 = 180

в) Посчитаем вручную, а затем сверим с numpy.

In [17]:
determinant = (1 * (5 * 9 - 8 * 6)) - (2 * (4 * 9 - 7 * 6)) + (3 * (4 * 8 - 5 * 7))
determinant

0

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(det(a), 10)

-0.0

С учетом округления аж до 10-ти знаков после запятой, мы видим, что определитель тоже равен нулю.

### Задание 2.
Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

Решение:

а) из 9-го свойства определителя: Для двух квадратных матриц одинакового размера

$$det(AB)=detA\cdot detB.$$

В нашем примере:

$$det(AA)=detA\cdot detA.$$

То есть:

$$ 4\cdot4=16 $$

б) Из первого свойство определителя: Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA.$$

а значит, что:

$$detA^{T}=detA=4$$

в) Из второго свойства: Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. 

Умножая матрицу на число, мы умножаем каждый элемент матрицы на это число, а значит, умножаем все строки на число $\lambda$. Соответственно, определитель станет в $\lambda^n$ (n - размерность матрицы) раз больше.

Наш пример:

$$det(2A) = 2^n\cdot4$$

### Задание 3.
Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Решение:

Умножим первый вектор (-2, 7, -3) на 2 и получим вектор (-4, 14, -6). Сложив получившийся вектор со вторым вектором этой марицы, мы получим нулевую строку. А по четверому свойству определителя - Если матрица имеет нулевую строку или столбец, то определитель равен нулю. Проверим это с помощью numpy:

In [19]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

det(a)

0.0

### Задание 4.
Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Решение:

а) Мы можем выразить третий вектор через два других:

$$(1, 2, 3) + (1, 1, 1) = (2, 3, 4)$$

Значит третий вектор можно убрать, остается матрица

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix};$

И ее ранг равен двум.

In [20]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

In [21]:
from numpy.linalg import matrix_rank

In [22]:
matrix_rank(a)

2

б) Решение:

Необходимо привести матрицу к треугольному виду, и посмотреть количество ненулевых строк.

Умножим первый столбец на 3/2, а второй столбец на -1:

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
3 & -3 & 5 & 6
\end{pmatrix}.$

сложим первый столбец со вторым, получим нулевой столбец, и уберем его:

$\begin{pmatrix}
0 & 2 & 1\\ 
0 & 2 & 2\\ 
0 & 4 & 3\\ 
-3 & 5 & 6
\end{pmatrix}.$

Поменяем 4-ую строку и 1-ую:

$\begin{pmatrix}
-3 & 5 & 6\\ 
0 & 2 & 2\\ 
0 & 4 & 3\\ 
0 & 2 & 1
\end{pmatrix}.$

Умножим 2-ую строку на 2 и вычтем из нее 3-ю строку:

$\begin{pmatrix}
-3 & 5 & 6\\ 
0 & 4 & 4\\ 
0 & 0 & 1\\ 
0 & 2 & 1
\end{pmatrix}.$

Умножим 4-ую строку на 2 и вычтем из 2-ой строки 4-ю строку:

$\begin{pmatrix}
-3 & 5 & 6\\ 
0 & 4 & 4\\ 
0 & 0 & 1\\ 
0 & 0 & 2
\end{pmatrix}.$

Умножим 3-ю строку на 2 и вычтем из 3-ей строки 4-ую, получим нулевую строку, которую можно отбросить:

$\begin{pmatrix}
-3 & 5 & 6\\ 
0 & 4 & 4\\ 
0 & 0 & 2
\end{pmatrix}.$

Получили треугольную матрицу размером 3х3, и ее ранк равен 3-ём.

In [23]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
matrix_rank(a)

3