In [1]:
import numpy as np
from numpy.linalg import det, eig

### Задание 1.
Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [2]:
A = np.array([[-1, -6], [2, 6]])

Найдем собственные значения, путем вычитания из главной диагонали линейного оператора $\lambda * E$:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-(-6)\cdot2=0,$$



$$-6 + \lambda -6\lambda +(\lambda)^{2} + 12=0,$$

$$(\lambda)^{2} -5\lambda + 6=0$$

Собственные значения:

$$\lambda_1 = 2\\\lambda_2=3$$

Собственные вектора:

$$\lambda_1 = 2: $$
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=
2
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.
$$



$$\begin{cases}
-x_1-6x_2=2x_1\\ 
2x_1+6x_2 = 2x_2\\
\end{cases}
\Rightarrow
\begin{cases}
x_1=-2x_2\\ 
x_2=x_2
\end{cases}\
\Rightarrow
\begin{cases}
x_1=-2\\ 
x_2=1
\end{cases}.$$

$$\lambda_1 = 3: $$
$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=
3
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.
$$



$$\begin{cases}
-x_1-6x_2=3x_1\\ 
2x_1+6x_2 = 3x_2\\
\end{cases}
\Rightarrow
\begin{cases}
x_1=-3/2x_2\\ 
x_2=x_2
\end{cases}\
\Rightarrow
\begin{cases}
x_1=-3/2\\ 
x_2=1
\end{cases}.$$

Собственные значения:

$\lambda_1 = 2\\
\lambda_2 = 3$

Собственные вектора:
$x_1 = (-2, 1)\\
x_2 = (-3/2, 1)$

Проверим, действительно ли вектора собственные?

In [3]:
x1 = np.array([-2, 1])
x2 = np.array([-3/2,1])

In [4]:
A.dot(x1) == 2*(x1)

array([ True,  True])

In [5]:
A.dot(x2) == 3*(x2)

array([ True,  True])

In [6]:
w, v = eig(A)
print('Собственные значения:\n', w)
print('Собственные вектора:\n', v)

Собственные значения:
 [2. 3.]
Собственные вектора:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


## Задание 2.
Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

In [7]:
A = np.array([[-1, 0], [0, -1]])

Зададим любой произвольный вектор, например $(-2, 1)$ и проверим чему будет равно произведение оператора на этот произвольный вектор:

In [8]:
x = np.array([-2, 1])

In [9]:
A.dot(x)

array([ 2, -1])

Судя по всему, любой вектор будет являться собственным, потому что, всегда найдется такая $\lambda$ (равная -1), которая будет являться решением для всех произвольно взятых векторов. Попробуем найти собственное значение оператора, чтобы убедиться в нашей теории:

Найдем собственные значения, путем вычитания из главной диагонали линейного оператора $\lambda * E$:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(-1-\lambda)-(0)\cdot0=0,$$

$$(-1-\lambda)(-1-\lambda)=0,$$

$$
\lambda_1 = \lambda_2 = -1 
$$




Найдем собственные вектора:

$$\lambda_1 = -1: $$
$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}=
-1
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}.
$$




$$\begin{cases}
-x_1=-x_1\\ 
-x_2 =-x_2\\
\end{cases}
\Rightarrow
\begin{cases}
x_1=\forall x_1\\
x_2=\forall x_2
\end{cases}
$$

Что и требовалось доказать.

## Задание 3.
Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\lambda_1 = ?: $$
$$\begin{pmatrix}
-1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\Rightarrow
\begin{cases}
\lambda=0\\ 
\lambda=2
\end{cases}
\Rightarrow
\lambda\nexists
$$

Одновременно не можем быть два значения $\lambda$ для одного собственного вектора.

## Задание 4.
Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=3.\\
\lambda=-3
\end{cases}
\Rightarrow
\lambda\nexists
$$

Одновременно не можем быть два значения $\lambda$ для одного собственного вектора.