In [1]:
import numpy as np
from numpy.linalg import det, matrix_rank, eig

## Практическое задание. Часть 1.

### Задание 1.

Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Решение:

Вычтем первую строку умноженную на 2 из 2-ой строки:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем первую строку из 3-ей строки:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Запишем получившуюся систему:
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4, \\
\end{cases}$$

Так как число уравнений меньше числа неизвестных, то такая система считается неопределенной и будет иметь бесконечное множество решений. Ниже, в коде, я выразил х3 через c, а затем выразил остальные неизвестные.

In [2]:
#Пусть x3 = C = 1
c = 1

In [3]:
x3 = c
x4 = (4+2*c)/3
x2 = x3 + 5*x4 + 2
x1 = x3 + (2/3)*(4+2*x3) - x2

print(f'При x3 = C = 1:\nx1={x1}\nx2={x2}\nx3={x3}\nx4={x4}')

При x3 = C = 1:
x1=-8.0
x2=13.0
x3=1
x4=2.0


In [4]:
print(f'Подставим получившиеся значения в систему уравнений и сверимся.\n\
𝑥1+𝑥2−𝑥3−2𝑥4 = {x1 + x2 - x3 - 2*x4}\n\
2𝑥1+𝑥2−𝑥3+𝑥4 = {2*x1 + x2 - x3 + x4}\n\
𝑥1+𝑥2−3𝑥3+𝑥4 = {x1 + x2 - 3*x3 + x4}\n\
Результат сходится.') 

Подставим получившиеся значения в систему уравнений и сверимся.
𝑥1+𝑥2−𝑥3−2𝑥4 = 0.0
2𝑥1+𝑥2−𝑥3+𝑥4 = -2.0
𝑥1+𝑥2−3𝑥3+𝑥4 = 4.0
Результат сходится.


### Задание 2.

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [5]:
a = np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
a_dop = np.array([[3,-1,1,4],[2,-5,-3,-17],[1,1,-1,0]])

In [6]:
def analyse_matrix(a, a_dop):
    if len(a[0]) == matrix_rank(a) and len(a[0]) == matrix_rank(a_dop):
        print('Система определена, и имеет единственное решение')
    elif len(a[0]) > matrix_rank(a) and matrix_rank(a) == matrix_rank(a_dop):
        print('Система имеет бесконечное количество решений')
    elif matrix_rank(a_dop) > matrix_rank(a):
        print('Система несовместна')
    else:
        return 'error'

In [7]:
analyse_matrix(a, a_dop)

Система определена, и имеет единственное решение


   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [8]:
a = np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
a_dop = np.array([[2,-4,6,1],[1,-2,3,-2],[3,-6,9,5]])

In [9]:
analyse_matrix(a, a_dop)

Система несовместна


   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


In [10]:
a = np.array([[1,2,5],[3,1,-8]])
a_dop = np.array([[1,2,5,4],[3,1,-8,-2]])

In [11]:
analyse_matrix(a, a_dop)

Система имеет бесконечное количество решений


### Задание 3.
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [12]:
a = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
a_dop = np.array([[1,3,-2,4,3],[0,5,0,1,2],[0,0,3,0,4],[0,0,0,2,1]])

In [13]:
analyse_matrix(a, a_dop)

Система определена, и имеет единственное решение


### Задание 4.
Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Согласно Теореме Кронекера — Капелли: если $rankA<rank \tilde A$, то система несовместна.

Нам дана дополненная матрица, определим матрицу $A$:

$$A=\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix}.$$

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

Ранг матрицы $A$ = 2:

In [15]:
matrix_rank(a)

2

Соответственно, ранг $\tilde{A}$ должен быть >2

Посмотрим на ранг $\tilde{A}$ и определим условие несовместимости:

Из второй строки вычтем первую, умноженную на 4:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c
\end{matrix}
\end{pmatrix}.$$

Из третей строчки вычтем первую, умноженную на 7:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{pmatrix}.$$

Из третей строчки вычтем вторую, умноженную на 2:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
(c - 7a) - 2(b - 4a)
\end{matrix}
\end{pmatrix}.$$

Видим, что ранг матрицы $A$ действительно равен 2. Соответственно, для того, чтобы ранг матрицы $\tilde{A}$ был больше 2-ух, необходимо, чтобы выражение $(c - 7a) - 2(b - 4a) \neq 0$. В противном случае, ранг матрицы $\tilde{A}$ так же будет равным 2-ум, а нас это не устраивает.

Раскрыв скобки, мы получаем следующее уравнение, при выполнении которого, система линейных уравнений, заданная расширенной матрицей $\tilde{A}$ несовместна: $$a - 2b + c \neq 0$$

Ведь, если это уравнение будет равно нулю, тогда мы сможем просто вычеркнуть последнюю строчку, и ранк $\tilde{A}$ станет равен двум, что противоречит условию несовместимости.

Придумаем такие $a, b, c$, что уравнение $a - 2b + c = 0$, в таком случае система уравнений будет совместима.
Например:

$$a=10\\b=18\\c=26$$

$$10 - 36 + 26 = 0$$

In [16]:
a_dop = np.array([[1,2,3,10],[4,5,6,18],[7,8,9,26]])
analyse_matrix(a, a_dop)

Система имеет бесконечное количество решений


Действительно, используя созданную функцию analyse_matrix, мы видим, что в таком случчае система имеет бесконечное кол-во решений.

Изменив $a=10$, например, на $a=12$ наше уравнение приобретает вид $a - 2b + c \neq 0$, и в таком случае, система уравнений становится несовместимой.

In [17]:
a_dop = np.array([[1,2,3,12],[4,5,6,18],[7,8,9,26]])
analyse_matrix(a, a_dop)

Система несовместна


## Практическое задание. Часть 2.

Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [18]:
a = np.array([[1, -2], [3, -4]])
print(f'Определитель матрицы = {round(det(a),0)}, а значит можно воспользоваться правилом Крамера.')

Определитель матрицы = 2.0, а значит можно воспользоваться правилом Крамера.


Определим дополнительные матрицы, получаемые заменой i-го столбца на вектор-столбец свободных членов b.

In [19]:
a_1 = np.array([[1, -2], [7, -4]])
a_1

array([[ 1, -2],
       [ 7, -4]])

In [20]:
a_2 = np.array([[1, 1], [3, 7]])
a_2

array([[1, 1],
       [3, 7]])

Находим решения системы уравнений:

In [21]:
x1 = round(det(a_1)/det(a),0)
x2 = round(det(a_2)/det(a),0)
print(f'x1 = {x1}\nx2 = {x2}')

x1 = 5.0
x2 = 2.0


    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [22]:
a = np.array([[2, -1, 5], [1, 1, -3],[2, 4, 1]])
print(f'Определитель матрицы = {round(det(a),0)}, а значит можно воспользоваться правилом Крамера.')

Определитель матрицы = 43.0, а значит можно воспользоваться правилом Крамера.


Определим дополнительные матрицы, получаемые заменой i-го столбца на вектор-столбец свободных членов b.

In [23]:
a_1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
a_1

array([[10, -1,  5],
       [-2,  1, -3],
       [ 1,  4,  1]])

In [24]:
a_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
a_2

array([[ 2, 10,  5],
       [ 1, -2, -3],
       [ 2,  1,  1]])

In [25]:
a_3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
a_3

array([[ 2, -1, 10],
       [ 1,  1, -2],
       [ 2,  4,  1]])

Находим решения системы уравнений:

In [26]:
x1 = round(det(a_1)/det(a),0)
x2 = round(det(a_2)/det(a),0)
x3 = round(det(a_3)/det(a),0)
print(f'x1 = {x1}\nx2 = {x2}\nx3 = {x3}')

x1 = 2.0
x2 = -1.0
x3 = 1.0


### Задание 2.
Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$


In [27]:
a = np.array([[1,2,4],[2,9,12],[3,26,30]])

Создадим функцию, для LU разложения матрицы: (Заодно сделаем задание 5)

In [28]:
def lu_decomposition(a):
    a_dop = np.identity(len(a))
    for i in range(len(a)):
        for j in range(len(a)):
            if i != j and j>=i:
                to_add = a[j][i]/a[i][i]
                a_dop[j][i] = to_add
                a[j] = a[j] - to_add*(a[i])
    return(a_dop, a)

In [29]:
L, U = lu_decomposition(a)

In [30]:
print(f'L = \n{L}\nU = \n{U}')

L = 
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]
U = 
[[1 2 4]
 [0 5 4]
 [0 0 2]]


    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [31]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])

In [32]:
L, U = lu_decomposition(a)

In [33]:
print(f'L = \n{L}\nU = \n{U}')

L = 
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]
U = 
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]


### Задача 3.
Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [34]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])

In [35]:
L, U = lu_decomposition(a)

In [36]:
print(f'L = \n{L}\nU = \n{U}')

L = 
[[1.  0.  0. ]
 [5.5 1.  0. ]
 [4.5 3.  1. ]]
U = 
[[  2   1   3]
 [  0   1 -11]
 [  0   0  24]]


Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
5.5y_{1}+y_{2}=-6, \\
4.5y_{1}+3y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-11.5,$$
$$y_{3}=25.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
x_{2} - 11x_{3}=-11.5, \\
24x_{3}=25.
\end{cases}$$

$$x_{3}=25/24,$$
$$x_{2}=-1/24,$$
$$x_{1}=-25/24.$$

### Задание 4.
Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [37]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ((-15) - (-5)\cdot(5) \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38 - 25 - 4}=3.$$


In [38]:
L_T = np.array([[ 9., -5.,  5.],
                [ 0.,  5.,  2.],
                [ 0.,  0.,  3.]])
L = L_T.T

In [39]:
L

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}= -33,$$

$$y_{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=-5,$$

$$x_{1}=6.$$

### Задание 5.
Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

Решено в Задании 2, функция lu_decomposition().